MODULE=scloud

IMPORTS=\
  tommath \
  tomcrypt \
  yajl

EXPORTS=\
  shared \
  src

INCLUDES=\
  shared \
  src

SOURCES=\
  shared/SCccm.c \
  shared/SCgcm.c \
  shared/SCkeys.c \
  shared/SCutilities.c \
  shared/SirenHash.c \
  shared/tomcryptwrappers.c \
  src/SCloud.c \
  src/SCloudJSON.c

include .module/Makefile
