MODULE=yajl

SOURCE_DIR=src

SOURCES=\
  yajl.c \
  yajl_alloc.c \
  yajl_buf.c \
  yajl_encode.c \
  yajl_gen.c \
  yajl_lex.c \
  yajl_parser.c \
  yajl_tree.c \
  yajl_version.c

include .module/Makefile
